package com.senao.warehouse.database;

public enum RECEIVING_TYPE {
    RECEIPTS, TEMP_RECEIPTS, TEMP_EMPLOY, DELETE,
    REC_COMBINE, REC_INVOICE, REC_PO, REC_COMBINE_INVOICE,
    TEMP_COMBINE, TEMP_INVOICE, TEMP_PO, TEMP_COMBINE_INVOICE,
    DEL_ERROR, DEL_PREDELIVER
}
